package Messenger;


/**
* Messenger/ClientContractOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contract.idl
* viernes 15 de abril de 2016 19H38' CEST
*/

public interface ClientContractOperations 
{
  String getName ();
  String sendMsg (String msg);
} // interface ClientContractOperations
