package Messenger;


/**
* Messenger/credentials.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contract.idl
* viernes 15 de abril de 2016 19H38' CEST
*/

public final class credentials implements org.omg.CORBA.portable.IDLEntity
{
  public String username = null;
  public String password = null;

  public credentials ()
  {
  } // ctor

  public credentials (String _username, String _password)
  {
    username = _username;
    password = _password;
  } // ctor

} // class credentials
