package Messenger;

/**
* Messenger/EchoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contract.idl
* viernes 15 de abril de 2016 19H38' CEST
*/

public final class EchoHolder implements org.omg.CORBA.portable.Streamable
{
  public Messenger.Echo value = null;

  public EchoHolder ()
  {
  }

  public EchoHolder (Messenger.Echo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Messenger.EchoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Messenger.EchoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Messenger.EchoHelper.type ();
  }

}
