package Messenger;

/**
* Messenger/ServerContractHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contract.idl
* viernes 15 de abril de 2016 19H38' CEST
*/

public final class ServerContractHolder implements org.omg.CORBA.portable.Streamable
{
  public Messenger.ServerContract value = null;

  public ServerContractHolder ()
  {
  }

  public ServerContractHolder (Messenger.ServerContract initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Messenger.ServerContractHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Messenger.ServerContractHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Messenger.ServerContractHelper.type ();
  }

}
