package Messenger;


/**
* Messenger/ServerContractOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contract.idl
* viernes 15 de abril de 2016 19H38' CEST
*/

public interface ServerContractOperations 
{
  boolean login (Messenger.credentials cred);
  boolean register (Messenger.credentials cred);
  Messenger.ClientContract getUser (String username);
  Messenger.ClientContract[] getFriends (String username);
} // interface ServerContractOperations
