package Example;


/**
* Example/Echo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from example_echo.idl
* jueves 14 de abril de 2016 16H53' CEST
*/

public interface Echo extends EchoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Echo
