package Example;


/**
* Example/EchoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from example_echo.idl
* jueves 14 de abril de 2016 16H53' CEST
*/

public interface EchoOperations 
{
  String echoString (String mesg);
} // interface EchoOperations
