package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* jueves 14 de abril de 2016 16H25' CEST
*/

public interface HelloOperations 
{
  String sayHello (String param);
  void shutdown ();
} // interface HelloOperations
