// omniidl -bpython Contract.idl

module Messenger {
  interface ClientContract{
    string getName();
    string sendMsg(in string username, in string msg);
    string transfer(in string path);
  };

  struct credentials{
    string username;
    string password;
    string IOR;
  };

  typedef sequence<ClientContract> usuarios;

  interface ServerContract{
    boolean login(in credentials cred);
    boolean register(in credentials cred);
    ClientContract getUser(in string username);
    usuarios getFriends(in string username);
  };

  interface Echo {
    string echoString(in string mesg);
  };
};