package Messenger;


/**
* Messenger/ClientContractOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contract.idl
* domingo 17 de abril de 2016 16H24' CEST
*/

public interface ClientContractOperations 
{
  String getName();
  String sendMsg(String username, String msg);
  String transfer(String path);
} // interface ClientContractOperations
