package Messenger;


/**
* Messenger/ServerContractOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contract.idl
* domingo 17 de abril de 2016 16H24' CEST
*/

public interface ServerContractOperations 
{
  boolean login(Messenger.credentials cred);
  boolean register(Messenger.credentials cred);
  Messenger.ClientContract getUser(String username);

  // Soon to be deprecated
  Messenger.ClientContract[] getFriends(String username);
  boolean makeFriends(String user1, String user2);
  String[] getFriendRequest(String user);
} // interface ServerContractOperations
