package Messenger;


/**
* Messenger/usuariosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contract.idl
* domingo 17 de abril de 2016 16H24' CEST
*/

public final class usuariosHolder implements org.omg.CORBA.portable.Streamable
{
  public Messenger.ClientContract value[] = null;

  public usuariosHolder ()
  {
  }

  public usuariosHolder (Messenger.ClientContract[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Messenger.usuariosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Messenger.usuariosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Messenger.usuariosHelper.type ();
  }

}
