# DO NOT EDIT THIS FILE!
#
# Python module Messenger generated by omniidl

import omniORB
omniORB.updateModule("Messenger")

# ** 1. Stub files contributing to this module
import Contract_idl

# ** 2. Sub-modules

# ** 3. End
