# DO NOT EDIT THIS FILE!
#
# Python module Messenger__POA generated by omniidl

import omniORB
omniORB.updateModule("Messenger__POA")

# ** 1. Stub files contributing to this module
import Contract_idl

# ** 2. Sub-modules

# ** 3. End
