package Messenger;

/**
* Messenger/ClientContractHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contract.idl
* sábado 16 de abril de 2016 18H57' CEST
*/

public final class ClientContractHolder implements org.omg.CORBA.portable.Streamable
{
  public Messenger.ClientContract value = null;

  public ClientContractHolder ()
  {
  }

  public ClientContractHolder (Messenger.ClientContract initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Messenger.ClientContractHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Messenger.ClientContractHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Messenger.ClientContractHelper.type ();
  }

}
