package Messenger;


/**
* Messenger/ClientContractHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contract.idl
* sábado 16 de abril de 2016 18H57' CEST
*/

abstract public class ClientContractHelper
{
  private static String  _id = "IDL:Messenger/ClientContract:1.0";

  public static void insert (org.omg.CORBA.Any a, Messenger.ClientContract that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Messenger.ClientContract extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Messenger.ClientContractHelper.id (), "ClientContract");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Messenger.ClientContract read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ClientContractStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Messenger.ClientContract value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Messenger.ClientContract narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Messenger.ClientContract)
      return (Messenger.ClientContract)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Messenger._ClientContractStub stub = new Messenger._ClientContractStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Messenger.ClientContract unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Messenger.ClientContract)
      return (Messenger.ClientContract)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Messenger._ClientContractStub stub = new Messenger._ClientContractStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
