package Messenger;

/**
* Messenger/credentialsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contract.idl
* sábado 16 de abril de 2016 18H57' CEST
*/

public final class credentialsHolder implements org.omg.CORBA.portable.Streamable
{
  public Messenger.credentials value = null;

  public credentialsHolder ()
  {
  }

  public credentialsHolder (Messenger.credentials initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Messenger.credentialsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Messenger.credentialsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Messenger.credentialsHelper.type ();
  }

}
