package Messenger;


/**
* Messenger/EchoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contract.idl
* sábado 16 de abril de 2016 18H57' CEST
*/

public interface EchoOperations 
{
  String echoString (String mesg);
} // interface EchoOperations
