package Messenger;


/**
* Messenger/requestsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contract.idl
* domingo 17 de abril de 2016 16H24' CEST
*/

public final class requestsHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public requestsHolder ()
  {
  }

  public requestsHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Messenger.requestsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Messenger.requestsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Messenger.requestsHelper.type ();
  }

}
