package Messenger;


/**
* Messenger/ServerContractOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contract.idl
* sábado 16 de abril de 2016 17H51' CEST
*/

public interface ServerContractOperations 
{
  boolean login (Messenger.credentials cred);
  boolean register (Messenger.credentials cred);
  Messenger.ClientContract getUser (String username);
  Messenger.ClientContract[] getFriends (String username);
} // interface ServerContractOperations
